distr_planner:
    optimized_script_filename: /tmp/optimized_script.sh
    output_dir: /tmp/distr_output
    fan_out: 1
    batch_size: 10000
    output_optimized: true
    distr_backend: false
    nodes:
      - "127.0.0.1"
      - "158.130.4.113"
      - "158.130.4.114"
      - "158.130.4.120"
