name: Pash-future-CI-issue
on:
  # Run the for-loop tests when pushing to future or when creating a new PR
  push:
    branches:
      - future
    paths: 
      - compiler/**
      - runtime/**
      - evaluation/**
      - annotations/**
  pull_request:
    branches:
      - future
    paths: 
      - compiler/**
      - runtime/**
      - evaluation/**
      - annotations/**
jobs:
  future-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Trigger Performance Tests
        run: |
          # fetch the commit hash
          hash=$(git rev-parse --short HEAD | tr -d "\n")
          # construct the url for performance and correctness
          tests="http://ctrl.pash.ndr.md/job=issue&branch=future&benchmark=TIGHT-LOOP&commit=$hash"
          # issue the tests for the future branch
          curl -s "$tests"
