name: Pash-Correctness-Tests
on: 
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    # the paths that trigger the ci
    paths: 
        - compiler/**
        - runtime/**
        - evaluation/**
        - annotations/**
# Jobs section
jobs:
    Pash-Tests:
      strategy:
        matrix:
          os: 
            - ubuntu-18.04
            - ubuntu-20.04
      runs-on: ${{ matrix.os }}
      if: github.event.pull_request.draft == false
      steps:
        - uses: actions/checkout@v2 
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Running-Pash-Benchmarks
          run: |
            # can't get to install directly via install.sh, so we build everything manually
            # export the optimized c++ aggregators
            export optimized_agg_flag=1
            # install the system deps and pash the environment
            sudo -E bash scripts/distro-deps.sh
            # install pash
            # the yes command actually fails for some weird Github Actions reason,
            # but it doesn't affect the operation since it just writes PASH_TOP
            # in the ~/*rc.sh files
            yes | sudo -E bash scripts/setup-pash.sh
            # build the aggregators manually
            cd runtime/;
            sudo -E make agg;
            cd ../;
            export PASH_TOP=$PWD
            export PATH=$PATH:$PASH_TOP
            cd scripts
            bash run_tests.sh  
            cd workflow
            bash parse.sh > results.log 2>&1  
            # get the timer
            d=$(LANG=en_us_88591; date)
            echo "VERSION<<EOF" >> $GITHUB_ENV
            echo "OS:${{matrix.os}}" >> $GITHUB_ENV
            echo "$d" >> $GITHUB_ENV
            # Parse the results and construct a github message post
            # we append the data to the global env
            cat results.log >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
        - name: Comment on PR
          uses: actions/github-script@v3
          with:
            script: |
              let body = `${{ env.VERSION }}`
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body,
              })     
        - name: Exit-code
          run: |
            cd scripts/workflow
            bash exit_code.sh
